### ISSUE TITLE
Cache-Control

### ISSUE THREAD

**Issue by BraunreutherA** [jthegedus/firebase-functions-next-example#17]
Hi there, 

I'm trying to cache the next.js response in the edges of the firebase cdn. Regarding to their tutorials it's as easy as adding `res.set("Cache-Control", "public, max-age=600, s-max-age=1200");` which I did. 
Do you know if there are any drawbacks? Don't want to run into them later on..

**Comment by beyony** [comment]
Hey,

I'm sorry, I can't tell about my experience since there aren't any yet.

Good luck

BAlex <notifications@github.com> schrieb am Di., 5. Juni 2018, 10:53:

**Comment by jthegedus** [comment]
My understanding was that when a new Firebase Hosting deployment occurs that the edge caches are flushed and so a stale cache shouldn't be a problem. I have not tested this myself to validate though, so can only go on what I have heard.

It would be interesting to know if the underlying Firebase Cloud Function is updated if the cache is expired or if that only occurs when Firebase Hosting is deployed again. Because if the CF is updated without publishing a new Hosting deployment then it may not flush the cache. Who knows :man_shrugging:

**Comment by jthegedus** [comment]
I am deprecating this example in favor of another approach, which can be found in this repo (https://github.com/jthegedus/firebase-gcp-examples/tree/master/functions-nextjs).
