### ISSUE TITLE
not working on new versions of nextjs 4 and react 16

### ISSUE THREAD

**Issue by alexandregiordanelli** [jthegedus/firebase-functions-next-example#8]
Ive updated the packages but stop working

**Comment by chanlito** [comment]
same here

**Comment by fabiozaffani** [comment]
Indeed

**Comment by jthegedus** [comment]
HI all, I'll be having a look at all these issues and updating the repo with fixes this coming weekend. Thanks for your patience.

**Comment by dav-is** [comment]
Update?

**Comment by jthegedus** [comment]
Sorry guys, life got in the way. I've got a solution to this, just need to clean some stuff up. I'll update the code this weekend followed by a new Medium post. It's a much simpler setup actually.

**Comment by yestoall** [comment]
is not working for me with nextjs 5

**Comment by jthegedus** [comment]
@yestoall can you please provide more information?

What warns/errors are in the browser console and the Firebase Cloud Function logs?

**Comment by yestoall** [comment]
i have this kind of errors in firebase console:
{ Error: Cannot find module 'babel-runtime/regenerator'     at Function.Module._resolveFilename (module.js:469:15)     at Function.Module._load (module.js:417:25)     at Module.require (module.js:497:17)     at require (internal/module.js:20:19)     at Object.<anonymous> (/user_code/next/dist/bundles/pages/_document.js:270:18)     at __webpack_require__ (/user_code/next/dist/bundles/pages/_document.js:23:31)     at Object.<anonymous> (/user_code/next/dist/bundles/pages/_document.js:101:84)     at __webpack_require__ (/user_code/next/dist/bundles/pages/_document.js:23:31)     at Object.module.exports.Object.defineProperty.value (/user_code/next/dist/bundles/pages/_document.js:92:18)     at __webpack_require__ (/user_code/next/dist/bundles/pages/_document.js:23:31) code: 'MODULE_NOT_FOUND' }
--

**Comment by jthegedus** [comment]
My latest update (~5 days ago) should provide a hotfix for this issue. A discussion of the issue can be found here - https://github.com/zeit/next.js/issues/3640 , with this comment https://github.com/zeit/next.js/pull/3886#issuecomment-368314752 on a PR revealing that it was a bug with Next.js. It is fixed in `yarn add next@canary`, so I would suggest you try that as a next step. When a Next.js v5 patch release fixes the issue I will again update this repo.

Let me know how you go with testing the `canary` version :smiley:

**Comment by yestoall** [comment]
thanks! now it's working
the only change i  make is using yarn instead of npm now

is any way to call the other firebase functions with short or cleaner url?
i mean https://us-central1-XXXXXX.cloudfunctions.net/greetings-mars

**Comment by jthegedus** [comment]
The clean URL for the Next.js application Cloud Function is coming from Firebase Hosting. So it only applies to functions that are Hosting rewrites. Since we want Next.js to handle all our routes and operate as a Single Page App I've used the rule

```json
 "hosting": {
    "public": "dist/public",
    "rewrites": [
      {
        "source": "**/**",
        "function": "app-next"
      }
    ],
  }
```

where all routes that hit our domain are processed by our Next.js app.

So those other Cloud Functions are just regular HTTPS Cloud Functions and have that URL signature. You could only change them to have the nice `yourdomain.com/greetings-mars` by having a rewrite rule for `/greetings-mars` to your `greetings-mars` Cloud Function. This however may result in Next.js SPA route problems.

I've got a code example in the works, but I've got other things to finish and publish before that, like my updated Next.js guide which is nearly done.

Thanks for your interest in this project, so not to constantly ping everyone else in this thread, if you have further questions feel free to create a new issue :smiley:
