### ISSUE TITLE
Can not deploy when dev = false

### ISSUE THREAD

**Issue by Thammada** [jthegedus/firebase-functions-next-example#9]
I got the following error when I set `dev = false`
in src/functions/index.js
```diff
-var dev = process.env.NODE_ENV !== "production"
+var dev = false
```

and try to deploy with `yarn deploy`
=== Deploying to 'nextjs-demo'...

i  deploying functions, hosting
i  functions: ensuring necessary APIs are enabled...
i  runtimeconfig: ensuring necessary APIs are enabled...
✔  runtimeconfig: all necessary APIs are enabled
✔  functions: all necessary APIs are enabled
i  functions: preparing dist/functions directory for uploading...

**Error: There was an unknown problem while trying to parse function triggers. Please ensure you are using Node.js v6 or greater.
error Command failed with exit code 2.**

the code deployed just fine when `dev == true`

I'm using macOS with
nvm 0.33.2
node 6.11.1
yarn 1.3.1

**Comment by didia** [comment]
Hello, 
Do you have any news on this one?  I would like to help debug this but I am new to firebase and next. I can't see any logs in firebase so I don't really understand what's going on under the cover.

**Comment by jthegedus** [comment]
This is an interesting one. I'm not sure why, but running

https://github.com/jthegedus/firebase-functions-next-example/blob/97e9921244a2a65c1aac9bf225fad93b36c2fa07/package.json#L35

works as expected. Which sets `dev = false`.

I've updated the repo to show this in the Firebase console:

https://github.com/jthegedus/firebase-functions-next-example/blob/97e9921244a2a65c1aac9bf225fad93b36c2fa07/src/functions/app/app.js#L10

Since we're not actually running the custom Next.js server when running `yarn dev` we don't use it in any other place other than on the Cloud Functions. And since we require `NODE_ENV=production` to get the local Cloud Function emulation to work there's no instance when we **need** to set `dev = true`.

I may look into running the Next.js server script during `yarn dev` in the future, but for the moment I would consider this solved.

If this answer is insufficient, then just comment asking for me to reopen it.
